#!/bin/bash

cat > .env <<EOF
NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
GITHUB_USER_ID=${GITHUB_USER_ID}
GITHUB_USERNAME=${GITHUB_USERNAME}
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_SECRET=${GITHUB_SECRET}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
AUTH_SECRET="${AUTH_SECRET}"
AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
AUTH_REDIRECT_PROXY_URL=${AUTH_REDIRECT_PROXY_URL}
NTFY_URL=${NTFY_URL}
NTFY_TOKEN=${NTFY_TOKEN}
LISTMONK_URL=${LISTMONK_URL}
LISTMONK_LIST_ID=${LISTMONK_LIST_ID}
LISTMONK_USERNAME=${LISTMONK_USERNAME}
LISTMONK_TOKEN=${LISTMONK_TOKEN}
EOF
